# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  name: hostpool

variables:
  pythonVersion: '3.10'

steps:
# 1. Checkout du code
- task: Checkout@1

# 2. Installer Python si nécessaire
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

# 3. Installer les dépendances 
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Installer les dépendances'

# 4. Valider le code 
- script: |
    echo "Exécution des tests unitaires 
    # pytest tests/  
  displayName: 'Valider le code'

# 5. Préparer le package pour publication
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
    replaceExistingArchive: true

# 6. Publier les artefacts pour pipeline CD
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
